import S2CPacket from '../S2CPacket'

export enum EntityStatus {
    ENTITY_HONEY_BLOCK_SLIDE_PARTICLES = 53,

    SNOWBALL_POOF_PARTICLES = 3,

    EGG_CRACK_PARTICLES = 3,

    FISHING_HOOK_PULL = 31,

    ARROW_TIPPED_PARTICLES = 0,

    FIREWORK_EXPLOSION = 17,

    LIVING_ENTITY_HURT = 2,
    LIVING_ENTITY_DEATH = 3,
    LIVING_ENTITY_SHIELD_BLOCK = 29,
    LIVING_ENTITY_SHIELD_BREAK = 30,
    LIVING_ENTITY_THORNS = 33,
    LIVING_ENTITY_TOTEM_OF_UNDYING = 35,
    LIVING_ENTITY_HURT_DROWN = 36,
    LIVING_ENTITY_HURT_BURN = 37,
    LIVING_ENTITY_HURT_SWEET_BERRY_BUSH = 44,
    LIVING_ENTITY_TELEPORT_PORTAL_PARTICLES = 46,
    LIVING_ENTITY_EQUIPMENT_BREAK_MAIN_HAND = 47,
    LIVING_ENTITY_EQUIPMENT_BREAK_OFF_HAND = 48,
    LIVING_ENTITY_EQUIPMENT_BREAK_HEAD = 49,
    LIVING_ENTITY_EQUIPMENT_BREAK_CHEST = 50,
    LIVING_ENTITY_EQUIPMENT_BREAK_LEGS = 51,
    LIVING_ENTITY_EQUIPMENT_BREAK_FEET = 52,
    LIVING_ENTITY_HONEY_BLOCK_FALL_PARTICLES = 54,
    LIVING_ENTITY_SWAP_HANDS = 55,
    LIVING_ENTITY_HURT_FREEZE = 57,
    LIVING_ENTITY_DEATH_SMOKE_PARTICLES = 60,

    PLAYER_FINISH_USE = 9,
    PLAYER_ENABLE_REDUCED_DEBUG_INFO = 22,
    PLAYER_DISABLE_REDUCED_DEBUG_INFO = 23,
    PLAYER_OP_0 = 24,
    PLAYER_OP_1 = 25,
    PLAYER_OP_2 = 26,
    PLAYER_OP_3 = 27,
    PLAYER_OP_4 = 28,
    PLAYER_BAD_OMEN_CLOUD = 43,

    ARMOR_STAND_HIT = 32,

    MOB_EXPLOSION_PARTICLE = 20,

    SQUID_RESET_ROTATION = 19,

    DOLPHIN_HAPPY = 38,

    ANIMAL_SEX = 18,

    HORSE_SMOKE_TAME_FAILED = 6,
    HORSE_HEARTS_TAME_SUCCEEDED = 7,

    OCELOT_SMOKE_TAME_FAILED = 40,
    OCELOT_HEARTS_TAME_SUCCEEDED = 41,

    RABBIT_JUMP = 1,

    SHEEP_EAT_GRASS = 40,

    FOX_CHEW_ITEM = 45,

    GOAT_LOWER_HEAD = 58,
    GOAT_STOP_LOWERING_HEAD = 59,

    TAMEABLE_SMOKE_TAME_FAILED = 6,
    TAMEABLE_HEARTS_TAME_SUCCEEDED = 7,

    WOLF_WATER_SHAKE = 8,
    WOLF_STOP_SHAKE = 56,

    VILLAGER_SEX = 12,
    VILLAGER_ANGRY = 13,
    VILLAGER_HAPPY = 14,
    VILLAGER_SPLASH = 42,

    IRON_GOLEM_ATTACK = 4,
    IRON_GOLEM_HOLD_OUT_POPPY = 11,
    IRON_GOLEM_PUT_AWAY_POPPY = 34,

    EVOKER_FANGS_ATTACK = 4,

    WITCH_MAGIC_PARTICLES = 15,

    RAVAGER_ATTACK = 4,
    RAVAGER_STUNNED = 39,

    ZOMBIE_VILLAGER_CURE = 16,

    GUARDIAN_ATTACK = 21,

    MINECART_TNT_IGNITE = 10,

    MINECART_SPAWNER_RESET_DELAY = 1,

    HOGLIN_ATTACK = 4,

    ZOGLIN_ATTACK = 4,
}

export default class S2CEntityStatusPacket extends S2CPacket {
    constructor(readonly entityID: number, readonly entityStatus: EntityStatus) {
        super(0x1b)

        this.packetBuffer.writeInt(entityID)
        this.packetBuffer.writeByte(entityStatus)
    }
}
